### ISSUE TITLE
Issue with unit display

### ISSUE THREAD

**Issue by AKrotchko** [Muspelful/QuickHit#2]
https://github.com/Muspelful/QuickHit/blob/ff755204ebd183152db66c2aa42f79a96be1bb05/src/main/Unit.java#L31

During my refactor, I left a sloppy error here. This should just say "Unit ", but I accidentally refactored the text to "src.main.Unit ". This also happened in a couple comments. You can see this problem in the screenshot I submitted.

**Comment by rlwhitin** [comment]
Thanks, I'll fix it in the morning.

**Comment by rlwhitin** [comment]
Hey, so, I looked at it for like two hours, and while the issue you mentioned was super easy to fix, I barely have any programming experience, and some of the other changes you made caused problems that I didn't even understand.

I really do appreciate the help, but I had to roll back the refactor because I've basically only taken two programming classes and I don't yet know how to work with this stuff very well, so I'll stick with the basics for now.
